main/models.py
from main import db


class Another(db.Model):
    id = db.Column(db.Integer(), unique=True, nullable=False, primary_key=True)
    title = db.Column(db.String(80), nullable=False )
    grouping = db.Column(db.Integer(), nullable=False )

    def __repr__(self):
        return self.title


class Entry(db.Model):
    id = db.Column(db.Integer(), unique=True, nullable=False, primary_key=True)
    title = db.Column(db.String(80), nullable=False )
    grouping = db.Column(db.Integer(), nullable=False )

    def __repr__(self):
        return "<title: {}>".format(self.title)

main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, IntegerField
from wtforms.widgets.html5 import NumberInput
from wtforms.validators import DataRequired, Length, Email, EqualTo
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from main.models import Another


class DataEntry(FlaskForm):
    grouping = IntegerField('Grouping',widget=NumberInput(), validators=[DataRequired()])
    title = QuerySelectField(
        'Title',
        query_factory=lambda: Another.query,
        allow_blank=False
    )
    submit = SubmitField('Add Record')


class DataEntryUpdate(DataEntry):
    submit = SubmitField('Update Record')

main/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
import os

app = Flask(__name__)
app.config['SECRET_KEY'] = '5791628bb0b13ce0c676dfde280ba255'
app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv("connectionString",'sqlite:///database.db')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)


def create_app():
    from main import routes
    from main.routes import main
    from errors.handlers import errors
    app.register_blueprint(main)
    app.register_blueprint(errors)
    return app
    

main/routes.py
from flask import render_template, request, Blueprint, flash, redirect, url_for
from main.forms import DataEntry, DataEntryUpdate
from main.models import Another
from main import db


main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    another = Another.query.all()
    return render_template('home.html', another=another)


@main.route("/new", methods=['GET', 'POST'])
def new():
    form = DataEntry()
    if form.validate_on_submit():
        data = Another(title=str(form.title.data), grouping=form.grouping.data)
        db.session.add(data)
        db.session.commit()
        flash('Your data has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('dataEntry.html', title='New Data', form=form)


@main.route("/data/<int:id>/delete", methods=['POST'])
def delete(id):
    record = Another.query.get(id)
    db.session.delete(record)
    db.session.commit()
    flash('Your record has been deleted!', 'success')
    return redirect(url_for('main.home'))

    
@main.route("/data/<int:id>/update", methods=['GET', 'POST'])
def update(id):
    record = Another.query.get(id)
    form = DataEntryUpdate()
    if form.validate_on_submit():
        record.title = str(form.title.data)
        record.grouping = form.grouping.data
        db.session.commit()
        flash('Your data has been updated!', 'success')
        return redirect(url_for('main.home'))
    elif request.method == 'GET':
        form.title.data = record.title
        form.grouping.data = record.grouping
    return render_template('dataEntry.html', title='Update Data', form=form, legend='Update Post')

main/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <script src="{{ url_for('static', filename='js/jquery-3.3.1.slim.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script>
      $(".btn").on("click", function() {
        $(this).prop("disabled", true);
        $(this).val('Please wait ...').attr('disabled','disabled');
    
      });
    </script>
  
    {% if title %}
        <title>Learning App - {{ title }}</title>
    {% else %}
        <title>Learning App</title>
    {% endif %}
  </head>
    <body class="pt-6" style='padding-top: 80px;'>
      <nav class="navbar navbar-dark bg-primary fixed-top navbar-expand-lg ">
        <a class="navbar-brand" href="/">Simple Crud APP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.home') }}?filter=4">Filter 4</a>
            </li>
          </ul>
        </div>
      </nav>


    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
    </main>
    
    </body>
</html>

main/templates/dataEntry.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">New Record</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.grouping.label(class="form-control-label") }}
                    {% if form.grouping.errors %}
                        {{ form.grouping(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.grouping.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.grouping(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

main/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <a class="btn btn-info" href="{{ url_for('main.new') }}">Add new record +</a>

  <h2>Topics</h2>
  <div>
    {% for entry in another %}
      <div class="row pt-2 content-section">
        <div class="col-2">
          {{entry.id}}
        </div>
        <div class="col-2">
          {{entry.grouping}}
        </div>
        <div class="col-2">
        {{entry.title}}
        </div>
        <a class="btn btn-info col-2" href="{{ url_for('main.update', id=entry.id) }}">Edit</a>
        <form  class="col-3" action="{{ url_for('main.delete', id=entry.id) }}" method="POST">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
      {% endfor %}
  </div>

{% endblock %}